### ISSUE TITLE
exercises.css sets fonts size in px

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#237]
The font size for formulas displayed in exercises is set to 14 or 15px. It should probably be in pt so it scales properly and in any case uses the same size as the surrounding text (14pt).

https://github.com/Carnap/Carnap/blob/93eb0c8897c99d0bdbe5dc3c3f695772cc9a2558/Carnap-Server/static/css/exercises.css#L131

**Comment by gleachkr** [comment]
I played with this a little, and I think it might be hard to change in isolation - bumping up the text size makes the input areas for translations bigger than the adjacent buttons, so those would need to be adjusted too - but then they look different from the buttons for other exercises... I think this should probably go with some of the layout changes from #19.

**Comment by rzach** [comment]
I can put it there although I noticed it in the model checker exercises where the formula is displayed. But I can fold it into #19  if you like.

**Comment by gleachkr** [comment]
I think it's ok to leave this as a separate issue - just kind of meant the above as a note that this is related to #19.

**Comment by dsanson** [comment]
Looking at this, I think the problem is caused by two things. First, the fact that translation and parsing exercises have different button placement. Second, the fact that the `<input>` boxes for translation and parsing exercises are styled by the same rules as the `<div class=.input>` boxes for the other exercises. That reflects a bigger difference: these are the only two exercise types for which the "input" box is a box that accepts actual input. Boxes that accept actual input should be styled differently than boxes that don't! (And probably these are the only exercises for which the choice of 'input' and 'output' as class names matches how they actually work.)

The simplest quick fix, which would improve the default appearance of all the exercises, is to separate out the CSS that styles the .input divs from the CSS that styles the input boxes. Keep the 14pt font size and 2em min-height for the input boxes, but not the .input divs:

```css
[data-carnap-type="truthtable"] > .input,
[data-carnap-type="countermodeler"] > .input,
[data-carnap-type="qualitative"] > .input,
[data-carnap-type="sequentchecker"] > .input,
[data-carnap-type="treedeductionchecker"] > .input {
    font-size:14pt;
    padding:5px;
    background:white;
    border:1px solid #A9B7C0;
    outline:none;
    margin:0px;
}

[data-carnap-type="synchecker"] > input,
[data-carnap-type="translate"] > input {
    font-size:14px;
    min-height:2em;
    padding:5px;
    background:white;
    border:1px solid #A9B7C0;
    outline:none;
    margin:0px;
}
```

This doesn't solve the bigger problem of aligning exercise font sizes with surrounding font sizes. That seems to me like it is part of a broader overhaul of the CSS, aimed at making it more easily customizable.
